email:
  address: "your_email@example.com"
  authorization_code: "your_authorization_code"
  imap_server: "imap.example.com"

download:
  start_date: "2025-10-07"  # 开始时间，后部的时分秒无效
  end_date: "2025-10-08"    # 结束时间，后部的时分秒无效
  save_dir: "./attachments"
  mailbox: "INBOX"#如果你切换了邮箱，需要修改此值