email:
  address: "your_email@example.com"
  authorization_code: "your_authorization_code"
  imap_server: "imap.example.com"

download:
  start_date: "2024-01-01"
  end_date: "2024-12-31"
  save_dir: "./attachments"